---
title: "Kobe Vis"
author: "Kento Shigyo"
date: "2023-10-13"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("tidyverse")
# install.packages("knitr")
library(dplyr)
# install.packages("kokudosuuchi")
library(ggplot2)
library(stringr)
library(readxl)
library(readr)
# library(kokudosuuchi)
# install.packages("rmapshaper")
# library(rmapshaper)
```


# Import data
```{r echo=FALSE}

d_daicho <- read_csv("./data/2023-juminkihondaicho.csv")
# d_daicho %>% 
  # select('種別') %>% unique() %>%
  # select('区') %>% unique() 
  # print()

# <区>
# 全市				
# 東灘区				
# 灘区				
# 中央区				
# 兵庫区				
# 北区				
# 長田区				
# 須磨区				
# 垂水区				
# 西区

# <種別>
# 人口(計)				
# 人口(男)				
# 人口(女)				
# 人口_日本人(計)				
# 人口_日本人(男)				
# 人口_日本人(女)				
# 人口_外国人(計)				
# 人口_外国人(男)				
# 人口_外国人(女)

```


```{r}
library(scales)

d_daicho_1 <- d_daicho %>% 
  # filter(区 == '全市') %>%
  filter(種別 == '人口(計)') %>% 
  filter(対象年月 == 202301) %>% 
  filter(支所等 == '本区' | 支所等 == '合計') %>%
  filter(区 != '北区' & 区 != '須磨区' & 区 != '西区')


d_daicho_2 <- d_daicho %>% 
  # filter(区 == '全市') %>%
  filter(種別 == '人口(計)') %>% 
  filter(対象年月 == 202301) %>% 
  filter(支所等 == '本区' | 支所等 == '合計') %>%
  filter(区 == '北区' | 区 == '須磨区' | 区 == '西区') %>% 
  group_by(区) %>% filter(値 == max(値)) 

d_daicho_districts <- union(d_daicho_1, d_daicho_2)
View(d_daicho_districts)

d_daicho_districts %>%
  filter(区 != '全市') %>% 
  # summarise(v = sum(値))
  ggplot() +
    geom_bar(aes(x=reorder(区, -値), y=値), stat="identity", fill="steelblue") +
    geom_text(aes(x=区, y=値, label=scales::comma(値)), vjust=-0.3) +
    ggtitle("神戸市の区ごとの人口数") +
    xlab("区") +
    ylab("人数") +
    scale_y_continuous(labels=comma) 

ggsave("./figures/population_by_wards.png", width=10, height=6, type="png")
    
  
  # exceptions
  # 北区, 須磨区, 西区
```


```{r}
# install.packages("sf")
# install.packages("RColorBrewer")
library(sf)
library(RColorBrewer)
# display.brewer.all()

# map <- read_sf("./data/Shape Files/chuoh/r2kb28110.shp")
# map <- read_sf("./data/Shape Files/higashinada/r2kb28101.shp")
# map <- read_sf("./data/Shape Files/hyogo/N03-21_28_210101.shp")

map <- read_sf("./data/Shape Files/kobe_districts/all_districts/all_districts.shp")

d_daicho_districts2 <- d_daicho_districts %>% rename(CITY_NAME=区)
View(d_daicho_districts2)

map2 <- map %>% 
  mutate(CITY_NAME = str_sub(CITY_NAME, 4,-1)) %>%
  left_join(d_daicho_districts2, by="CITY_NAME") %>% 
  select(CITY_NAME, AREA, 値) %>% rename(population=値)


ggplot(map2) + geom_sf()

ggplot(map2) + geom_sf(aes(fill=population)) +
  scale_fill_gradientn(colors=brewer.pal(11,"GnBu"), labels=comma) +
  # scale_fill_continuous(labels=comma) +
  # theme(axis.text.y = element_blank(), axis.text.x = element_blank(), axis.ticks = element_blank()) +
  # geom_text(aes(label=CITY_NAME), vjust=-0.3) +
  theme_void() +
  geom_text(aes(x = 135.18, y = 34.8), label = "北区", color="white", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.04, y = 34.72), label = "西区", color="white", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.06, y = 34.65), label = "垂水区", color="white", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.108, y = 34.67), label = "須磨区", color="black", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.215, y = 34.67), label = "中央区", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.227, y = 34.72), label = "灘区", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.27, y = 34.72), label = "東灘区", color="white", family = "HiraKakuProN-W3", angle=0) +
  
  geom_text(aes(x = 135.145, y = 34.67), label = "長", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.147, y = 34.658), label = "田", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.149, y = 34.646), label = "区", color="black", family = "HiraKakuProN-W3", angle=0) +
  
  geom_text(aes(x = 135.165, y = 34.68), label = "兵", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.170, y = 34.665), label = "庫", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.175, y = 34.65), label = "区", color="black", family = "HiraKakuProN-W3", angle=0) +
  labs(fill = "単位：人") +
  ggtitle("神戸市各区の人口")
```
```{r}
ggplot(map2) + geom_sf()

map3 <- map2 %>% 
  mutate(population_density = population / AREA)

ggplot(map3) + geom_sf(aes(fill=population_density)) +
  scale_fill_gradientn(colors=brewer.pal(11,"GnBu"), labels=comma) +
  # scale_fill_continuous(labels=comma) +
  # theme(axis.text.y = element_blank(), axis.text.x = element_blank(), axis.ticks = element_blank()) +
  # geom_text(aes(label=CITY_NAME), vjust=-0.3) +
  theme_void() +
  geom_text(aes(x = 135.18, y = 34.8), label = "北区", color="black", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.04, y = 34.72), label = "西区", color="black", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.06, y = 34.65), label = "垂水区", color="black", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.108, y = 34.67), label = "須磨区", color="black", family = "HiraKakuProN-W3") +
  geom_text(aes(x = 135.215, y = 34.67), label = "中央区", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.227, y = 34.72), label = "灘区", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.27, y = 34.72), label = "東灘区", color="black", family = "HiraKakuProN-W3", angle=0) +
  
  geom_text(aes(x = 135.145, y = 34.67), label = "長", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.147, y = 34.658), label = "田", color="black", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.149, y = 34.646), label = "区", color="black", family = "HiraKakuProN-W3", angle=0) +
  
  geom_text(aes(x = 135.165, y = 34.68), label = "兵", color="white", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.170, y = 34.665), label = "庫", color="white", family = "HiraKakuProN-W3", angle=0) +
  geom_text(aes(x = 135.175, y = 34.65), label = "区", color="white", family = "HiraKakuProN-W3", angle=0) +
  labs(fill = "単位：人/km2") +
  ggtitle("神戸市各区の人口密度")


```




```{r}
d_city_ward_offices <- read_csv("./data/city_ward_offices.csv")

ggplot(map2) +
  geom_sf()  +
  geom_point(
    data=d_city_ward_offices,
    aes(x=経度, y=緯度, color=分類),
    stat="identity",
    position="identity",
    alpha=0.5
  ) +
  # ops(legend.position="top")
  scale_color_discrete(breaks=c("市役所", "区役所", "支所")) +
  ggtitle("神戸市内の市役所・区役所・支所の位置")


```

```{r}
d_location_wifi <- read_csv("./data/location_free_wifi.csv")

ggplot(map2) +
  geom_sf()  +
  geom_point(
    data=d_location_wifi,
    aes(x=経度, y=緯度),
    stat="identity",
    position="identity",
    alpha=0.5
  ) +
  # ops(legend.position="top")
  scale_color_discrete(breaks=c("市役所", "区役所", "支所")) +
  ggtitle("Kobe Free Wi-Fiアクセスポイント一覧")
```


  
  
  
  
  