---
title: "Youtube Data"
author: "Kento Shigyo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("tidyverse")
library(tidyverse)
```


**Load dataset**
```{r label='load_dataset', message=FALSE}
data <- read_csv('./Global YouTube Statistics.csv')
```


**Show headlines**
```{r label='headlines'}
data %>% 
  head(3) %>%
  view()
  # select(rank, Youtuber, subscribers, Country) %>% 
  # rename(Rank=rank, Subscribers=subscribers) %>% 
  # knitr::kable()
```

**Summary of the data**
```{r}
data %>% nrow()  # 955 youtubers
data %>% 
  select(Country) %>% unique() %>% arrange(Country)
```


**Order by Youtubers and country**
```{r}
data %>% 
  group_by(Country) %>%
  summarise(num_youtubers=n()) %>% 
  arrange(desc(num_youtubers)) %>% 
  mutate(highlight = ifelse(Country == "Japan", TRUE, FALSE)) %>% 
  ggplot(aes(x=reorder(Country, num_youtubers), y=num_youtubers)) +
    geom_bar(stat="identity", aes(fill=highlight)) +
    scale_fill_manual(values = c('gray', 'red'), guide=FALSE) +
    geom_text(aes(label=num_youtubers),  vjust = 0.5, nudge_y = 10, size=3) +
    coord_flip() +
    labs(title="The number of youtubers by countries") +
    ylab("The number of youtuers") +
    xlab("Country")
```
```{r}
data %>% 
  group_by(Country) %>%
  summarise(num_youtubers=n()) %>% 
  arrange(desc(num_youtubers)) %>% 
  head(23) %>% 
  mutate(highlight = ifelse(Country == "Japan", TRUE, FALSE)) %>% 
  ggplot(aes(x=reorder(Country, num_youtubers), y=num_youtubers)) +
    geom_bar(stat="identity", aes(fill=highlight)) +
    scale_fill_manual(values = c('gray', 'red'), guide=FALSE) +
  　geom_text(aes(label=num_youtubers),  vjust = 0.5, nudge_y = 10, size=3) +
    coord_flip() +
    labs(title="The number of youtubers by top 23 countries") +
    ylab("The number of youtuers") +
    xlab("Country")
```



**Japanese top youtuebrs**

```{r}
data %>% 
  filter(Country == "Japan") 
```

### Questions
- Category
  - What are popular category worldwide?
  - Does some country has trendy category? by cultural preference?
  - Relaitonship with category and video views?
  
## About category
**popular video category worldwide**
```{r}
data %>% 
  select(rank, category, Country, subscribers, `video views`) %>% 
  arrange(rank) %>% head(10) %>% 
  knitr::kable()
```


```{r}
data %>% 
  group_by(category) %>% 
  summarise(num_categories=n()) %>% 
  arrange(desc(num_categories)) %>% 
  knitr::kable()
```
```{r}
data %>% 
  group_by(category) %>% 
  summarise(num_categories=n()) %>% 
  arrange(desc(num_categories)) %>% 
  ggplot(aes(x=reorder(category, num_categories), y=num_categories)) +
    geom_bar(stat="identity") +
  　geom_text(aes(label=num_categories),  vjust = 0.5, nudge_y = 10, size=3) +
    coord_flip() +
    labs(title="The number of categories in the world") +
    ylab("The number of categories") +
    xlab("Category")

```


```{r}
# install.packages("treemapify")
# install.packages("ggfittext")
library(treemapify)

# data %>% select(category) %>% unique() 

data %>% 
  group_by(category) %>% 
  summarise(num_categories=n()) %>% 
  arrange(desc(num_categories)) %>% 
  ggplot(aes(area=num_categories, label=category, fill=num_categories)) +
    geom_treemap() +
    geom_treemap_text(fontface = "italic", colour = "white", place = "centre", grow = TRUE)
 
```







